Raúl Correa Ocañas

A01722401

28 / 11 / 2024

# Examen Argumentativo - RAFA

In [1]:
import numpy as np
import pandas as pd
from tqdm import tqdm
from matplotlib import pyplot as plt

In [2]:
class Machine:
    def __init__(self, rate=0):
        self.rate = rate
        self.task_list = []
    
    def add_task(self, task):
        self.task_list.append(task)

    def calc_time(self):
        time = 0

        for task in self.task_list:
            time += task.n_elements / self.rate

        return time

class Task:
    def __init__(self, n_elements=0):
        self.n_elements = n_elements

In [3]:
def MonteCarlo(n_simulations):

    # Problem Params

    n_tasks_choices = (20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30) # (Lower, Upper) Uniforme Estandar Entero
    n_elements_choices = (10, 20, 30) # (Opciones) Uniforme Estandar Entero
    n_machines_choices = [3, 4, 5] # (Opciones) Uniforme Estandar Entero
    machine_rate_choices = [5, 10, 15] # (Opciones) Uniforme Estandar Entero
    
    registers = {}

    for idx in range(n_simulations):

        n_tasks = np.random.randint(20, 31)
        tasks = [Task() for i in range(n_tasks)]

        # Populate the tasks for simulation
        for task in tasks:
            # Set number of elements per task
            rand_n = np.random.random()
            rand_n = rand_n * 30

            if rand_n <= 10:
                n_elements = 10
            elif rand_n <= 20:
                n_elements = 20
            else:
                n_elements = 30
            
            task.n_elements = n_elements

        ################

        n_machines = np.random.randint(3, 6)
        machines = [Machine() for i in range(n_machines)]

        # Populate the machines for simulation

        for machine in machines:
            rand_n = np.random.random()
            rand_n = rand_n * 15

            if rand_n <= 5:
                rate = 5
            elif rand_n <= 10:
                rate = 10
            else:
                rate = 15

            machine.rate = rate

        ###########################
        # Populate tasks to each machine

        for task in tasks:
            rand_n = np.random.randint(n_machines)
            machines[rand_n].add_task(task)

        ########################

        makespans = [machine.calc_time() for machine in machines]

        registers[idx] = [
            round(np.max(makespans), 4),
            round(np.mean(makespans), 4),
            round(np.min(makespans), 4),
        ]
    
    results_df = pd.DataFrame(
        index=['Max', 'Mean', 'Min'],
        data=registers
    ).T

    print(results_df.mean())

    return results_df

In [4]:
n_simulations = int(input('Enter number of simulations'))
MonteCarlo(n_simulations)

Max     26.846667
Mean    15.887668
Min      7.176665
dtype: float64

        Max     Mean      Min
0   22.0000  11.9167   4.6667
1   24.0000  15.3333   4.0000
2   28.0000  12.8333   5.3333
3   14.0000  11.1667   9.3333
4   18.0000   9.7333   6.6667
..      ...      ...      ...
95  14.0000   7.4667   3.3333
96  32.0000  16.8000   4.0000
97  10.6667   7.8667   4.0000
98  48.0000  31.0000  13.0000
99  30.0000  17.2500  11.0000

[100 rows x 3 columns]

# Conclusiones

Se concluye que mediante 20 simulaciones de los diferentes parametros aleatorios que pueden ser escogidos, el promedio en caso maximo fueron 30 unidades de tiempo, el caso promedio es de 17.5 unidades de tiempo y el caso promedio minimo es de 8.4 unidades de tiempo.